import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  emptySources: {
    flex: 1,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptySourcesInner: {
    width: '100%',
    maxWidth: 345,
    alignItems: 'center',
    gap: 16,
  },
  centerTitle: {
    color: '#002576',
    fontSize: 30,
    lineHeight: 38,
    fontWeight: '600',
    textAlign: 'center',
  },
  centerText: {
    color: '#444653',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '400',
    textAlign: 'center',
  },
  sourceLimitText: {
    color: '#747685',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '500',
    textAlign: 'center',
  },
  uploadButton: {
    width: '100%',
    marginTop: 16,
    backgroundColor: '#fecb00',
    borderWidth: 1,
    borderColor: 'rgba(196,197,213,0.3)',
    borderRadius: 12,
    paddingVertical: 25,
    paddingHorizontal: 33,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 1,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  disabledUploadButton: {
    opacity: 0.55,
  },
  uploadButtonText: {
    color: '#1a1c1c',
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '600',
  },
  uploadProgressCard: {
    width: '100%',
    gap: 8,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#c4c5d5',
    backgroundColor: '#ffffff',
  },
  uploadProgressTitle: {
    color: '#002576',
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '700',
  },
  uploadProgressDetail: {
    color: '#444653',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
  },
  uploadProgressTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: '#d8e1ff',
    overflow: 'hidden',
  },
  uploadProgressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#0038a8',
  },
  uploadProgressMeta: {
    color: '#747685',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
  },
  pressedScale: {
    transform: [{ scale: 0.97 }],
  },
  tabScroll: {
    flex: 1,
  },
  sourcesContent: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 156,
    gap: 20,
  },
  tabletTabContent: {
    width: '100%',
    maxWidth: 980,
    alignSelf: 'center',
    paddingHorizontal: 32,
  },
  sourceList: {
    gap: 10,
    overflow: 'visible',
    zIndex: 1,
  },
  sourceCard: {
    position: 'relative',
    alignItems: 'center',
    gap: 4,
    padding: 9,
    borderRadius: 8,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(196,197,213,0.2)',
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
    zIndex: 1,
  },
  activeSourceCard: {
    zIndex: 1000,
    elevation: 1000,
  },
  sourceMenuButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    zIndex: 1002,
    elevation: 1002,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 12,
  },
  sourceMenu: {
    position: 'absolute',
    top: 34,
    right: 8,
    zIndex: 1001,
    width: 168,
    padding: 8,
    borderRadius: 12,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(196,197,213,0.4)',
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 1001,
  },
  sourceMenuItem: {
    minHeight: 40,
    borderRadius: 8,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  menuItemPressed: {
    backgroundColor: '#f4f5f7',
  },
  sourceMenuText: {
    color: '#1a1c1c',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
  },
  sourceMenuDangerText: {
    color: '#93000A',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
  },
  pdfIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#ffdad6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sourceName: {
    maxWidth: '100%',
    color: '#444653',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    letterSpacing: 0.6,
  },
  sourceStatus: {
    maxWidth: '100%',
    color: '#747685',
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '500',
    textAlign: 'center',
  },
  readyStatus: {
    color: '#166534',
  },
  failedStatus: {
    color: '#93000A',
  },
  confirmContent: {
    gap: 12,
  },
  confirmText: {
    color: '#444653',
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '400',
  },
  renameInput: {
    minHeight: 52,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#c4c5d5',
    backgroundColor: '#ffffff',
    color: '#1a1c1c',
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '500',
    paddingHorizontal: 14,
  },
  saveButton: {
    minHeight: 50,
    borderRadius: 12,
    backgroundColor: '#002576',
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveButtonText: {
    color: '#ffffff',
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
  },
  removeButton: {
    minHeight: 50,
    borderRadius: 12,
    backgroundColor: '#E12531',
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeButtonText: {
    color: '#ffffff',
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
  },
  keepButton: {
    minHeight: 46,
    borderRadius: 12,
    backgroundColor: '#eeeeee',
    alignItems: 'center',
    justifyContent: 'center',
  },
  keepButtonText: {
    color: '#1a1c1c',
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
  },
});
