import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  tabScroll: {
    flex: 1,
  },
  toolsContent: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 40,
    gap: 24,
  },
  tabletTabContent: {
    width: '100%',
    maxWidth: 980,
    alignSelf: 'center',
    paddingHorizontal: 32,
  },
  toolsTitle: {
    color: '#002576',
    fontSize: 30,
    lineHeight: 38,
    fontWeight: '700',
    letterSpacing: 0,
    marginBottom: 8,
  },
  toolsDescription: {
    color: '#444653',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '400',
  },
  toolsStatusText: {
    marginTop: 12,
    color: '#747685',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
  },
  toolCards: {
    gap: 16,
  },
  tabletToolCards: {
    flexDirection: 'row',
  },
  toolCard: {
    position: 'relative',
    overflow: 'hidden',
    padding: 25,
    borderRadius: 12,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(196,197,213,0.3)',
    shadowColor: '#000',
    shadowOpacity: 0.02,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 4 },
    elevation: 1,
  },
  disabledToolCard: {
    opacity: 0.55,
  },
  tabletToolCard: {
    flex: 1,
  },
  pressedScale: {
    transform: [{ scale: 0.97 }],
  },
  redAccent: {
    position: 'absolute',
    width: 96,
    height: 96,
    borderBottomLeftRadius: 96,
    backgroundColor: 'rgba(225,37,49,0.05)',
    top: -35,
    right: -31,
  },
  yellowAccent: {
    position: 'absolute',
    width: 96,
    height: 96,
    borderBottomLeftRadius: 96,
    backgroundColor: 'rgba(209,166,0,0.05)',
    top: -31,
    right: -31,
  },
  quizIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(225,37,49,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  flashcardIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(209,166,0,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  toolTitle: {
    color: '#1a1c1c',
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600',
    marginBottom: 4,
  },
  toolDescription: {
    color: '#444653',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '400',
    marginBottom: 16,
  },
  chevronRow: {
    alignItems: 'flex-end',
  },
  chevronCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#eeeeee',
    alignItems: 'center',
    justifyContent: 'center',
  },
  toolScreen: {
    flex: 1,
    backgroundColor: '#f8f8f8',
  },
  toolScreenHeader: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 16,
    gap: 4,
  },
  backButton: {
    alignSelf: 'flex-start',
    minHeight: 36,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  backArrow: {
    color: '#002576',
    fontSize: 22,
    lineHeight: 26,
    fontWeight: '600',
  },
  backText: {
    color: '#002576',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  toolScreenTitle: {
    color: '#002576',
    fontSize: 30,
    lineHeight: 38,
    fontWeight: '700',
    letterSpacing: 0,
  },
  toolScreenSubtitle: {
    color: '#444653',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
  },
  toolSessionContent: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 40,
    gap: 16,
  },
  toolControls: {
    borderRadius: 12,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(196,197,213,0.35)',
    padding: 16,
    gap: 12,
  },
  toolControlLabel: {
    color: '#1a1c1c',
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '700',
  },
  countOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  countOption: {
    minWidth: 48,
    minHeight: 38,
    borderRadius: 10,
    backgroundColor: '#eeeeee',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  selectedCountOption: {
    backgroundColor: '#002576',
  },
  countOptionText: {
    color: '#1a1c1c',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  selectedCountOptionText: {
    color: '#ffffff',
  },
  generateButton: {
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: '#002576',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  disabledGenerateButton: {
    opacity: 0.55,
  },
  generateButtonText: {
    color: '#ffffff',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  toolStatusText: {
    color: '#444653',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
  },
  quizSummaryCard: {
    borderRadius: 12,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(196,197,213,0.35)',
    padding: 16,
    gap: 10,
  },
  quizSummaryTitle: {
    color: '#002576',
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '700',
  },
  quizSummaryText: {
    color: '#444653',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '400',
  },
  quizModeToggle: {
    flexDirection: 'row',
    gap: 8,
  },
  quizModeButton: {
    minHeight: 36,
    flex: 1,
    borderRadius: 10,
    backgroundColor: '#eeeeee',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  selectedQuizModeButton: {
    backgroundColor: '#002576',
  },
  quizModeButtonText: {
    color: '#1a1c1c',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  selectedQuizModeButtonText: {
    color: '#ffffff',
  },
  quizProgressTrack: {
    width: '100%',
    height: 8,
    borderRadius: 999,
    backgroundColor: '#eeeeee',
    overflow: 'hidden',
  },
  quizProgressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#fecb00',
  },
  quizCard: {
    padding: 22,
    borderRadius: 12,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(196,197,213,0.3)',
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  quizCounter: {
    color: '#747685',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
    letterSpacing: 0.6,
  },
  quizQuestion: {
    color: '#1a1c1c',
    fontSize: 18,
    lineHeight: 26,
    fontWeight: '600',
    marginTop: 8,
    marginBottom: 22,
  },
  optionList: {
    gap: 10,
  },
  optionButton: {
    width: '100%',
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#f8f8f8',
    borderWidth: 1,
    borderColor: '#c4c5d5',
  },
  selectedOption: {
    backgroundColor: '#eef2ff',
    borderColor: '#0038a8',
  },
  correctOption: {
    backgroundColor: 'rgba(34,197,94,0.1)',
    borderColor: 'rgba(34,197,94,0.5)',
  },
  wrongOption: {
    backgroundColor: 'rgba(225,37,49,0.1)',
    borderColor: 'rgba(225,37,49,0.5)',
  },
  optionText: {
    color: '#1a1c1c',
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '500',
  },
  answerCard: {
    marginTop: 14,
    borderRadius: 12,
    backgroundColor: '#eef2ff',
    padding: 14,
    gap: 4,
  },
  answerText: {
    color: '#002576',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  answerExplanation: {
    color: '#444653',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '400',
  },
  quizNavigation: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  quizActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingTop: 4,
  },
  quizActionPrimary: {
    minHeight: 42,
    borderRadius: 12,
    backgroundColor: '#002576',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  quizSubmitButton: {
    flexGrow: 1,
  },
  quizActionPrimaryText: {
    color: '#ffffff',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  quizActionSecondary: {
    minHeight: 42,
    borderRadius: 12,
    backgroundColor: '#eeeeee',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  quizActionSecondaryText: {
    color: '#1a1c1c',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  disabledAction: {
    opacity: 0.45,
  },
  flashcardProgressRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  flashcardHint: {
    color: '#747685',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '500',
  },
  flashcardReviewCard: {
    minHeight: 280,
    position: 'relative',
    borderRadius: 12,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(196,197,213,0.3)',
    padding: 22,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  flippedFlashcardReviewCard: {
    backgroundColor: '#fff8dd',
    borderColor: 'rgba(254,203,0,0.55)',
  },
  flashcardFaceLabel: {
    position: 'absolute',
    top: 20,
    left: 22,
    color: '#0038a8',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
    letterSpacing: 0.6,
  },
  flashcardReviewBody: {
    width: '100%',
    minHeight: 170,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    paddingTop: 18,
  },
  flashcardReviewScroller: {
    width: '100%',
    maxHeight: 230,
  },
  flashcardReviewScrollerContent: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 4,
  },
  flashcardReviewText: {
    color: '#1a1c1c',
    fontSize: 20,
    lineHeight: 30,
    fontWeight: '700',
    textAlign: 'center',
  },
  flashcardBackReviewText: {
    fontSize: 18,
    lineHeight: 27,
    fontWeight: '600',
  },
  flashcardLongReviewText: {
    fontSize: 16,
    lineHeight: 24,
  },
  scoreModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.36)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  scoreModalCard: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 12,
    backgroundColor: '#ffffff',
    padding: 22,
    gap: 10,
  },
  scoreModalEyebrow: {
    color: '#747685',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
    letterSpacing: 0,
  },
  scoreModalTitle: {
    color: '#002576',
    fontSize: 34,
    lineHeight: 42,
    fontWeight: '700',
  },
  scoreModalText: {
    color: '#444653',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
  },
  scoreModalActions: {
    gap: 8,
    paddingTop: 8,
  },
  scoreModalButton: {
    width: '100%',
  },
});
