import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  tabScroll: {
    flex: 1,
  },
  toolsContent: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 40,
    gap: 24,
  },
  tabletTabContent: {
    width: '100%',
    maxWidth: 980,
    alignSelf: 'center',
    paddingHorizontal: 32,
  },
  toolsTitle: {
    color: '#002576',
    fontSize: 30,
    lineHeight: 38,
    fontWeight: '700',
    letterSpacing: 0,
    marginBottom: 8,
  },
  toolsDescription: {
    color: '#444653',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '400',
  },
  toolsStatusText: {
    marginTop: 12,
    color: '#747685',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
  },
  toolCards: {
    gap: 16,
  },
  tabletToolCards: {
    flexDirection: 'row',
  },
  toolCard: {
    position: 'relative',
    overflow: 'hidden',
    padding: 25,
    borderRadius: 12,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(196,197,213,0.3)',
    shadowColor: '#000',
    shadowOpacity: 0.02,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 4 },
    elevation: 1,
  },
  disabledToolCard: {
    opacity: 0.55,
  },
  tabletToolCard: {
    flex: 1,
  },
  pressedScale: {
    transform: [{ scale: 0.97 }],
  },
  redAccent: {
    position: 'absolute',
    width: 96,
    height: 96,
    borderBottomLeftRadius: 96,
    backgroundColor: 'rgba(225,37,49,0.05)',
    top: -35,
    right: -31,
  },
  yellowAccent: {
    position: 'absolute',
    width: 96,
    height: 96,
    borderBottomLeftRadius: 96,
    backgroundColor: 'rgba(209,166,0,0.05)',
    top: -31,
    right: -31,
  },
  quizIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(225,37,49,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  flashcardIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(209,166,0,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  toolTitle: {
    color: '#1a1c1c',
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600',
    marginBottom: 4,
  },
  toolDescription: {
    color: '#444653',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '400',
    marginBottom: 16,
  },
  chevronRow: {
    alignItems: 'flex-end',
  },
  chevronCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#eeeeee',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
