import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  chatRoot: {
    flex: 1,
  },
  chatScroll: {
    flex: 1,
  },
  chatContent: {
    flexGrow: 1,
    justifyContent: 'flex-end',
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 12,
  },
  chatContentKeyboardFocused: {
    justifyContent: 'flex-start',
    paddingBottom: 16,
  },
  keyboardScrollSpacer: {
    height: 156,
  },
  tabletTabContent: {
    width: '100%',
    maxWidth: 980,
    alignSelf: 'center',
    paddingHorizontal: 32,
  },
  chatIntro: {
    gap: 8,
  },
  chatIntroTitle: {
    color: '#002576',
    fontSize: 30,
    lineHeight: 38,
    fontWeight: '600',
  },
  chatIntroText: {
    color: '#444653',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '400',
  },
  aiStatusText: {
    color: '#747685',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '500',
    marginTop: 4,
  },
  messageList: {
    gap: 12,
  },
  messageRow: {
    flexDirection: 'row',
  },
  messageRowUser: {
    justifyContent: 'flex-end',
  },
  messageRowAI: {
    justifyContent: 'flex-start',
  },
  messageBubble: {
    maxWidth: '88%',
    minWidth: 0,
    flexShrink: 1,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  userBubble: {
    backgroundColor: '#0038a8',
    borderBottomRightRadius: 4,
  },
  aiBubble: {
    backgroundColor: '#ffffff',
    borderBottomLeftRadius: 4,
  },
  messageText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '400',
    flexShrink: 1,
    flexWrap: 'wrap',
  },
  userMessageText: {
    color: '#ffffff',
  },
  aiMessageText: {
    color: '#444653',
  },
  markdownBlock: {
    gap: 6,
    minWidth: 0,
  },
  markdownHeading: {
    color: '#002576',
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
  },
  markdownSubheading: {
    fontSize: 16,
    lineHeight: 22,
  },
  markdownParagraph: {
    color: '#444653',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '400',
    minWidth: 0,
    flexShrink: 1,
    flexWrap: 'wrap',
  },
  markdownBold: {
    fontWeight: '700',
  },
  markdownListRow: {
    flexDirection: 'row',
    gap: 8,
    minWidth: 0,
  },
  markdownListMarker: {
    width: 24,
    flexShrink: 0,
    color: '#0038a8',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  sourcesUsed: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(196,197,213,0.5)',
    gap: 4,
  },
  sourcesUsedTitle: {
    color: '#002576',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
  },
  sourcesUsedText: {
    color: '#747685',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    flexShrink: 1,
    flexWrap: 'wrap',
  },
  analysisText: {
    marginTop: 10,
    color: '#747685',
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '500',
  },
  studyResultButton: {
    marginTop: 12,
    minHeight: 42,
    borderRadius: 12,
    backgroundColor: '#eef2ff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  studyResultButtonText: {
    color: '#002576',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  typingBubble: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: '#ffffff',
    borderRadius: 16,
    borderBottomLeftRadius: 4,
  },
  typingDots: {
    width: 42,
    minHeight: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  typingDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#747685',
  },
  chatInputArea: {
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 4,
    backgroundColor: '#f9f9f9',
  },
  chatInputDock: {
    width: '100%',
  },
  studyPanel: {
    flex: 1,
    backgroundColor: '#f8f8f8',
  },
  studyPanelOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 20,
    elevation: 20,
  },
  studyPanelHeader: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(196,197,213,0.25)',
  },
  studyPanelTitle: {
    color: '#002576',
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '700',
  },
  studyPanelClose: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#c4c5d5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  studyPanelCloseText: {
    color: '#1a1c1c',
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '700',
  },
  chatInputBar: {
    backgroundColor: '#e8e8e8',
    borderWidth: 1,
    borderColor: '#c4c5d5',
    borderRadius: 999,
    paddingLeft: 12,
    paddingRight: 6,
    paddingVertical: 2,
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
  },
  chatInput: {
    flex: 1,
    color: '#1a1c1c',
    fontSize: 14,
    fontWeight: '400',
    paddingVertical: 0,
  },
  disabledChatInput: {
    opacity: 0.55,
  },
  voiceButton: {
    marginLeft: 4,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#c4c5d5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  listeningVoiceButton: {
    backgroundColor: '#e12531',
    borderColor: '#e12531',
  },
  disabledVoiceButton: {
    opacity: 0.5,
  },
  sendButton: {
    marginLeft: 4,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#002576',
    alignItems: 'center',
    justifyContent: 'center',
  },
  disabledSendButton: {
    opacity: 0.5,
  },
  pressedScale: {
    transform: [{ scale: 0.97 }],
  },
  tabScroll: {
    flex: 1,
  },
  quizContent: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 40,
    gap: 20,
  },
  emptyStudyPanel: {
    flex: 1,
    padding: 24,
    justifyContent: 'center',
    gap: 8,
  },
  quizSummaryCard: {
    borderRadius: 14,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(196,197,213,0.35)',
    padding: 16,
    gap: 10,
  },
  quizSummaryTitle: {
    color: '#002576',
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '700',
  },
  quizSummaryText: {
    color: '#444653',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '400',
  },
  quizProgressTrack: {
    width: '100%',
    height: 8,
    borderRadius: 999,
    backgroundColor: '#eeeeee',
    overflow: 'hidden',
  },
  quizProgressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#fecb00',
  },
  quizActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingTop: 4,
  },
  quizNavigation: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  quizActionPrimary: {
    minHeight: 42,
    borderRadius: 12,
    backgroundColor: '#002576',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  quizSubmitButton: {
    flexGrow: 1,
  },
  quizActionPrimaryText: {
    color: '#ffffff',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  quizActionSecondary: {
    minHeight: 42,
    borderRadius: 12,
    backgroundColor: '#eeeeee',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  quizActionSecondaryText: {
    color: '#1a1c1c',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  quizNoticeCard: {
    borderRadius: 14,
    backgroundColor: '#fff8dd',
    borderWidth: 1,
    borderColor: 'rgba(254,203,0,0.55)',
    padding: 16,
    gap: 8,
  },
  quizNoticeTitle: {
    color: '#7a4b00',
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '700',
  },
  quizNoticeText: {
    color: '#444653',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '400',
  },
  quizNoticeButton: {
    alignSelf: 'flex-start',
    minHeight: 36,
    borderRadius: 10,
    backgroundColor: '#002576',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  quizNoticeButtonText: {
    color: '#ffffff',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  disabledAction: {
    opacity: 0.45,
  },
  quizCounter: {
    color: '#747685',
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 0.6,
  },
  quizCard: {
    padding: 24,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(196,197,213,0.3)',
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  answerCard: {
    marginTop: 14,
    borderRadius: 12,
    backgroundColor: '#eef2ff',
    padding: 14,
    gap: 4,
  },
  answerText: {
    color: '#002576',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  answerExplanation: {
    color: '#444653',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '400',
  },
  quizQuestion: {
    color: '#1a1c1c',
    fontSize: 18,
    lineHeight: 26,
    fontWeight: '600',
    marginBottom: 24,
  },
  optionList: {
    gap: 10,
  },
  optionButton: {
    width: '100%',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#f8f8f8',
    borderWidth: 1,
    borderColor: '#c4c5d5',
  },
  selectedOption: {
    backgroundColor: '#eef2ff',
    borderColor: '#0038a8',
  },
  correctOption: {
    backgroundColor: 'rgba(34,197,94,0.1)',
    borderColor: 'rgba(34,197,94,0.5)',
  },
  wrongOption: {
    backgroundColor: 'rgba(225,37,49,0.1)',
    borderColor: 'rgba(225,37,49,0.5)',
  },
  optionText: {
    color: '#1a1c1c',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '400',
  },
  quizOpenInput: {
    minHeight: 112,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#c4c5d5',
    backgroundColor: '#f8f8f8',
    color: '#1a1c1c',
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '400',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  flashcardDeck: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 40,
    gap: 16,
  },
  flashcardReviewCard: {
    flex: 1,
    minHeight: 260,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(196,197,213,0.3)',
    padding: 22,
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  flashcardSideLabel: {
    color: '#0038a8',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
    letterSpacing: 0.6,
  },
  flashcardReviewText: {
    color: '#1a1c1c',
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '700',
  },
  flashcardHint: {
    color: '#747685',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '500',
  },
  flashcardActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
  },
});
